
import type { KaomojiCategory } from '../types';

export const kaomojiData: KaomojiCategory[] = [
  {
    category: 'Symbol Combos',
    kaomojis: [
      { name: 'Beaming', value: '(★ω★)' },
      { name: 'Celebrating', value: '(ﾉ´ヮ´)ﾉ*:･ﾟ✧' },
      { name: 'Woot', value: '\\(★ω★)/' },
      { name: 'So Happy', value: '☆*:.｡.o(≧▽≦)o.｡.:*☆' },
      { name: 'Flipping Off', value: '(凸ಠ益ಠ)凸' },
      { name: 'Boom', value: '(☄ฺ◣д◢)☄ฺ' },
      { name: 'Heart Arrow', value: '(｡･ω･｡)ﾉ♡' },
      { name: 'You & Me', value: '♡(⇀ 3 ↼)♡' },
      { name: 'Stargazing Together', value: '☆(・ω・)人(・ω・)☆' },
      { name: 'Magic Trick', value: '(∩^o^)⊃━☆ﾟ.*･｡' },
      { name: 'Butterfly', value: 'Ƹ̵̡Ӝ̵̨̄Ʒ' },
      { name: 'Peace Sign', value: '(✌ﾟ∀ﾟ)☞' },
      { name: 'Twinkle', value: '(๑•̀ㅂ•́)و✧' },
      { name: 'Star Eyes', value: '(๑☆‿ ☆#)ᕗ' },
      { name: 'Vampire', value: '◥(º▽º)◤' },
      { name: 'Summoning', value: '(∩｀-´)⊃━☆ﾟ.*･｡ﾟ' },
      { name: 'Toast!', value: '( ´∀｀)っ凵☆凵c(´∀｀ )' },
      { name: 'Money Eyes', value: '(💲ω💲)' },
      { name: 'Music Notes', value: '🎵( ´θ｀)ノ🎵' },
      { name: 'Rainy Day', value: 'ヽ`､ヽ`☂o(･ω･｡)`ヽ､`ヽ､' },
    ],
  },
  {
    category: 'Emoji Combos',
    kaomojis: [
      { name: 'Gardening', value: '(・∀・)🌸' },
      { name: 'Hiding Knife', value: '(＾ω＾)🔪' },
      { name: 'Dango', value: '(o・-・)っ🍡' },
      { name: 'Noodle Slurp', value: '( ´ ▽ ` )ﾉ🍜' },
      { name: 'Sparkles', value: '✨( ´ ▽ ` )✨' },
      { name: 'Love Arrow', value: '( ˘⌣˘)🏹(˘⌣˘ )' },
      { name: 'Flower Crown', value: '🌸(˘⌣˘)🌸' },
      { name: 'Rocket Launch', value: '🚀(ง`̀-\'́)ง🚀' },
      { name: 'Pizza Love', value: '🍕( ♥ ω ♥ )' },
      { name: 'Ghost', value: '👻( ,,>з<)' },
      { name: 'Alien Wave', value: '👽( ´ ▽ ` )ﾉ' },
      { name: 'Gaming', value: '( ´ ▽ ` )ﾉ 🎮' },
      { name: 'Brainy', value: '🧠(°∀°)🧠' },
      { name: 'Thinking Face', value: '(´-`).｡oO(🤔)' },
      { name: 'Cupid Arrow', value: '(｡> ω <｡)💘' },
      { name: 'Taking Shower', value: '🚿⊂(´・ω・｀⊂)' },
      { name: 'Gone Fishing', value: '〜(・ω・)〜🎣' },
      { name: 'Happy Giraffe', value: '🦒ヽ(•‿•)ノ' },
      { name: 'Fierce Lion', value: '(◣_◢)o-o-o🦁' },
      { name: 'Dinosaur Stomp', value: '🦖( V)o\o(V )' },
      { name: 'Magical Unicorn', value: '🦄✨(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧' },
      { name: 'Dragon\'s Glare', value: '🐉(-`д´-🐉)' },
      { name: 'Sharing a Secret', value: '🤫(・x・)' },
      { name: 'Angel Wings', value: '👼( ´ ▽ ` )' },
      { name: 'Angry Mask', value: '👺( ` ω ´ )' },
      { name: 'Skull and Crossbones', value: '☠(×_×)☠' },
      { name: 'Birthday Celebration', value: '🎂ヽ( ´ ▽ ` )ﾉ' },
      { name: 'Decorating Tree', value: '🎄( ´ ▽ ` )ﾉ' },
      { name: 'Working on Computer', value: '💻( ・ω・)´' },
      { name: 'On The Phone', value: '📱(・_・;)' },
      { name: 'Reading a Book', value: '📖φ(．．;)' },
      { name: 'Coffee Break', value: '( ´ー｀)y-~~☕' },
      { name: 'Angry Cloud', value: '💢☁(＃`Д´)' },
      { name: 'King', value: '👑( ´ ▽ ` )' },
      { name: 'Queen', value: '👸( ´ ▽ ` )' },
      { name: 'Detective Investigating', value: '🕵️(･_├┬┴┬┴' },
      { name: 'Scientist with Potion', value: '🧑‍🔬⚗️(・∀・)' },
      { name: 'Artist Painting', value: '🧑‍🎨🎨( ´ ▽ ` )' },
      { name: 'Astronaut Floating', value: '🧑‍🚀🚀( ´ ▽ ` )' },
      { name: 'Firefighter to the Rescue', value: '🧑‍🚒🚒( ´ ▽ ` )' },
    ],
  },
  {
    category: 'Happy & Joyful',
    kaomojis: [
      { name: 'Happy', value: '(^ω^)' },
      { name: 'Grinning', value: '(´∀｀)' },
      { name: 'Laughing', value: '(>▽<)' },
      { name: 'Smiling', value: '(*^▽^*)' },
      { name: 'Joyful', value: '＼(￣▽￣)／' },
      { name: 'Excited', value: 'ヽ(・∀・)ﾉ' },
      { name: 'Content', value: '(´｡• ᵕ •｡`)' },
      { name: 'Sparkling', value: 'キラキラ(☆∀☆)' },
      { name: 'Thumbs Up', value: '(b^ω^)b' },
      { name: 'Cheering', value: 'o(〃＾▽＾〃)o' },
      { name: 'Pleased', value: '(⌒‿⌒)' },
      { name: 'Victorious', value: '(^_^)v' },
      { name: 'Glee', value: 'o(>ω<)o' },
      { name: 'Delighted', value: '(*´∀`*)' },
      { name: 'Triumphant', value: 'ヽ( ´ ▽ ` )ﾉ' },
      { name: 'Party', value: '٩( ᐛ )و' },
      { name: 'Blissful', value: '(๑>◡<๑)' },
      { name: 'Content Smile', value: '(´_ゝ｀)' },
      { name: 'Chillin', value: '(￣▽￣)ノ' },
      { name: 'Fist Pump', value: 'o(>◡<)o' },
      { name: 'Happy Dance', value: 'ヘ( ^o^)ノ＼(^_^ )' },
      { name: 'Waving Flag', value: '(╯✧▽✧)╯' },
      { name: 'So Touched', value: '(´感動｀)' },
    ],
  },
  {
    category: 'Sad & Crying',
    kaomojis: [
      { name: 'Crying', value: '(;´Д｀)' },
      { name: 'Sobbing', value: '(T_T)' },
      { name: 'Sad', value: '｡･ﾟﾟ･(>д<)･ﾟﾟ･｡' },
      { name: 'Depressed', value: '(-_-)' },
      { name: 'Tears', value: '(´;ω;`)' },
      { name: 'Heartbroken', value: '(╯︵╰,)' },
      { name: 'Gloomy', value: '（；＿；）' },
      { name: 'Giving Up', value: '／(^o^)＼' },
      { name: 'Trembling', value: '((´д｀))' },
      { name: 'Sigh', value: '(´Д｀)' },
      { name: 'Sniffle', value: '(´-ω-`)' },
      { name: 'Wounded', value: '(×_×)' },
      { name: 'Melancholy', value: '(´･_･`)' },
      { name: 'Despair', value: '|(￣3￣)|' },
      { name: 'Hurt', value: '(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)' },
      { name: 'Pain', value: '(ノ_<。)' },
      { name: 'Upset', value: '(＃＞＜)' },
      { name: 'Distraught', value: 'o(>< )o' },
      { name: 'Sulking', value: '(｡•́︿•̀｡)' },
      { name: 'Weeping', value: '(╥_╥)' },
      { name: 'Disappointed', value: '(´_｀)' },
      { name: 'Empty', value: '(´・_・｀)' },
      { name: 'Waterfall Tears', value: '( ཀ͝ ∧ ཀ͝ )' },
      { name: 'Fetal Position', value: '_(」∠ ､ﾝ､)_' },
      { name: 'Utter Despair', value: '絶望した' },
      { name: 'Drowning in Tears', value: '... sinking ...' },
      { name: 'Broken', value: '💔' },
    ],
  },
  {
    category: 'Angry & Annoyed',
    kaomojis: [
      { name: 'Angry', value: '(＃`Д´)' },
      { name: "Furious", value: 'ヽ( `д´*)ノ' },
      { name: 'Table Flip', value: '(╯°□°）╯︵ ┻━┻' },
      { name: 'Frustrated', value: '(>_<)' },
      { name: 'Annoyed', value: '(-`д´-)' },
      { name: 'Pissed', value: '(`⌒´メ)' },
      { name: 'Mad', value: '(╬ Ò﹏Ó)' },
      { name: 'Dual Table Flip', value: '┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻' },
      { name: 'Grumpy', value: '(￣^￣)' },
      { name: 'Punch', value: '(ง’̀-‘́)ง' },
      { name: 'Irate', value: '٩(╬ʘ益ʘ╬)۶' },
      { name: 'Fuming', value: '（-""-；)' },
      { name: 'Yelling', value: '(((p(>o<)q)))' },
      { name: 'Exasperated', value: '(-_-#)' },
      { name: 'Scowling', value: '(¬_¬")' },
      { name: 'Rage', value: '(ò_óˇ)' },
      { name: 'Gun', value: '(・∀・)・∀・)・∀・)・∀・)・∀・)⌐■-■' },
      { name: 'Sword Fight', value: '(-_(-_(-_(-_-)_-)-_-)-_-)' },
      { name: 'Chainsaw', value: '୧༼ಠ益ಠ༽୨' },
      { name: 'Get out', value: '( ´Д｀)ﾉ~' },
      { name: 'Cracking Knuckles', value: 'ポキポキ' },
      { name: 'Death Glare', value: '( ` ω ´ )' },
      { name: 'Throwing Chair', value: '(ノಠ益ಠ)ノ彡┻━┻' },
      { name: 'Hmph', value: '( ´-ω-)' },
      { name: 'Don\'t talk to me', value: '( -_-)旦~' },
    ],
  },
  {
    category: 'Love & Affection',
    kaomojis: [
      { name: 'Love', value: '(｡♥‿♥｡)' },
      { name: 'Kiss', value: '(づ￣ ³￣)づ' },
      { name: 'Blushing', value: '⁄(⁄ ⁄•⁄-⁄•⁄ ⁄)⁄' },
      { name: 'Hug', value: '(ɔˆ ³(ˆ⌣ˆc)' },
      { name: 'Wink', value: '(^_-)' },
      { name: 'In Love', value: '(*♡∀♡)' },
      { name: 'Adore', value: '(´,,•ω•,,)♡' },
      { name: 'Giving Flower', value: '( ´ ∀ ` )ノ～ ♡' },
      { name: 'Heart Eyes', value: '(♥ω♥*)' },
      { name: 'Shy Love', value: '(//∇//)' },
      { name: 'Blowing Kiss', value: '(*￣з￣)' },
      { name: 'Offering Heart', value: '（*’∀’人）♥' },
      { name: 'Couple Kiss', value: '(❤´³`❤)' },
      { name: 'Couple Hug', value: 'ヽ(♡‿♡)ノ' },
      { name: 'Warm Smile', value: '(´⌣`ʃƪ)' },
      { name: 'Flirty Wink', value: '(~_~;)' },
      { name: 'Secret Love', value: '|･ω･｀)' },
      { name: 'Proposing', value: '跪いて許しを請う' },
      { name: 'Holding Hands', value: '(^v^)/' },
      { name: 'Cuddling', value: '(っ´ω`c)' },
      { name: 'I Love You', value: '愛してる' },
      { name: 'Sharing Umbrella', value: '相合傘' },
      { name: 'My Precious', value: '(´,,>ω<,,`)' },
    ],
  },
  {
    category: 'Actions',
    kaomojis: [
      { name: 'Dancing', value: '♪~ ᕕ(ᐛ)ᕗ' },
      { name: 'Running', value: 'ε=ε=┌( >_<)┘' },
      { name: 'Hiding', value: '┬┴┬┴┤(･_├┬┴┬┴' },
      { name: 'Writing', value: 'φ(．．;)' },
      { name: 'Sleeping', value: '(－_－) zzZ' },
      { name: 'Waving', value: '( ´ ▽ ` )ﾉ' },
      { name: 'Apologizing', value: 'm(_ _)m' },
      { name: 'Thinking', value: '(・－・)?' },
      { name: 'Binoculars', value: '(◎ ◎)ゞ' },
      { name: 'Salute', value: '(￣^￣)ゞ' },
      { name: 'Facepalm', value: '(－‸ლ)' },
      { name: 'Whistling', value: '(・ε・)' },
      { name: 'Pointing', value: '(☞ﾟ∀ﾟ)☞' },
      { name: 'Peeking', value: '(|lﾟДﾟ|l)' },
      { name: 'Bowing Deeply', value: '土下座' },
      { name: 'Smoking', value: '( ´ー｀)y-~~' },
      { name: 'Drinking Tea', value: '(っ´ω`)ﾉ( ´ω`c)' },
      { name: 'Taking Picture', value: '［(－－)］' },
      { name: 'Clapping', value: "(´∀｀ﾉﾉ'ﾟﾁ'ﾟﾁ)" },
      { name: 'Walking Away', value: '...ε(*´･ω･)ﾉﾞ' },
      { name: 'Eating', value: '( ´З｀)＝３' },
      { name: 'Reading', value: 'φ(．．)' },
      { name: 'Summoning', value: '༼ つ ◕_◕ ༽つ' },
    ],
  },
  {
    category: 'Animals',
    kaomojis: [
      { name: 'Cat', value: '(=^･ω･^=)' },
      { name: 'Dog', value: '(´・(oo)・｀)' },
      { name: 'Bear', value: '(´(エ)｀)' },
      { name: 'Rabbit', value: '（・ｘ・）' },
      { name: 'Pig', value: '(´・(oo)・｀)' },
      { name: 'Bird', value: '（・⊝・）' },
      { name: 'Fish', value: '<・)))><<' },
      { name: 'Owl', value: '(・o・)' },
      { name: 'Spider', value: '/╲/\\╭(•‿•)╮/\\╱\\' },
      { name: 'Squid', value: '＜コ：ミ' },
      { name: 'Monkey', value: '@(o･ｪ･o)@' },
      { name: 'Koala', value: '(￣(工)￣)' },
      { name: 'Panda', value: '(´･(ｴ)･｀)' },
      { name: 'Fox', value: '/(・ x ・)\\' },
      { name: 'Whale', value: '＞°）mニニニニ＝～' },
      { name: 'Snail', value: '＠ノ”' },
      { name: 'Bat', value: '（＾（´（´・（´・（´・ω・）´・）`）´）＾）' },
      { name: 'Centipede', value: 'εїз' },
      { name: 'Jellyfish', value: '(:)彡' },
      { name: 'Crab', value: 'V=(° °)=V' },
      { name: 'Mouse', value: '~~(・x・)~~' },
      { name: 'Bee', value: 'ε===(っ≧ω≦)っ' },
    ],
  },
  {
    category: 'Miscellaneous',
    kaomojis: [
      { name: 'Shrug', value: '¯\\_(ツ)_/¯' },
      { name: 'Confused', value: '(°_°)' },
      { name: 'Surprised', value: '(o_O)' },
      { name: 'Scared', value: '(((;°Д°)))' },
      { name: 'Magic', value: '୧(﹒︠ᴗ﹒︡)୨' },
      { name: 'Cool Glasses', value: '(⌐■_■)' },
      { name: 'Meh', value: '┐(￣ヘ￣)┌' },
      { name: 'Whatever', value: '╮( ˘ ､ ˘ )╭' },
      { name: 'Disapproval', value: '( ¬_¬)' },
      { name: 'Money', value: '[̲̅$̲̅(̲̅ιο̲̅̅)̲̅$̲̅]' },
      { name: 'Nervous', value: '(⌒_⌒;)' },
      { name: 'Worried', value: '(・_・;)' },
      { name: 'Music', value: 'ヽ(⌐■_■)ノ♪♬' },
      { name: 'High Five', value: '( ´∀｀)人(´∀｀ )' },
      { name: 'Why not?', value: 'ヽ( ´¬`)ノ' },
      { name: 'What?', value: '(・_・ヾ' },
      { name: 'Doubt', value: '(´-ι_-｀)' },
      { name: 'Speechless', value: '( speechless... )' },
      { name: 'Nodding', value: '(*・ω・)(*-ω-)(*・ω・)(*-ω-)' },
      { name: 'Shaking Head', value: '摇头' },
      { name: 'Come here', value: 'おいで' },
      { name: 'Good night', value: 'おやすみ' },
      { name: 'Leaving', value: 'ε=ε=ε=ε=┌(;￣◇￣)┘' },
      { name: 'Bless you', value: '(´人｀)' },
      { name: 'Good morning', value: 'おはよう' },
      { name: 'Welcome back', value: 'おかえり' },
    ],
  },
  {
    category: 'Cute & Adorable',
    kaomojis: [
      { name: 'Fluffy', value: '(´｡• ◡ •｡`)' },
      { name: 'Sparkly Eyes', value: '(*^.^*)' },
      { name: 'Shy', value: '(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)' },
      { name: 'Peeking', value: '(⁄ ⁄•⁄ω⁄•⁄ ⁄)' },
      { name: 'Peaceful Sleep', value: '(ᵕ.ᵕ)' },
      { name: 'Little Bear', value: '(͒ ˊ• ૢ·̫•ˋ ૢ)' },
      { name: 'Flower', value: '✿( ´ ▽ ` )' },
      { name: 'Tiny', value: '(´• ω •`)' },
      { name: 'Kawaii', value: '(｡> ω <｡)' },
      { name: 'Puffy Cheeks', value: '( ´͈ ॢꇴ `͈ॢ)･*♡' },
      { name: 'Puppy Eyes', value: '(o´ω`o)' },
      { name: 'Chubby', value: '( • )( • )' },
      { name: 'Innocent', value: '(´• . • `)' },
      { name: 'Headpat', value: '( ´・ω・)ﾉ(´・ω・｀)' },
      { name: 'Snuggle', value: '( ´ ▽ ` ).｡ｏ♡' },
      { name: 'So cute', value: 'ヾ(〃^∇^)ﾉ' },
      { name: 'Sweet Dream', value: '(-ω-ゞ' },
      { name: 'Giggle', value: '( *´艸`)' },
      { name: 'Precious', value: '(ﾉ´ з `)ノ' },
      { name: 'Small Smile', value: '(*¯︶¯*)' },
      { name: 'Floating', value: '둥실둥실' },
      { name: 'Begging', value: '(人◕ω◕)' },
      { name: 'Hiding in Box', value: '[_|_]' },
    ],
  },
  {
    category: 'Sinister & Sly',
    kaomojis: [
      { name: 'Evil Grin', value: '(ψ▼w▼)ψ' },
      { name: 'Devious', value: '(¬‿¬)' },
      { name: 'Plotting', value: '( V)o\o(V )' },
      { name: 'Villain Laugh', value: 'ψ(｀∇´)ψ' },
      { name: 'Side Eye', value: '( →_→)' },
      { name: 'Peeking Evilly', value: '|дﾟ)' },
      { name: 'Dark Aura', value: '((╬◣﹏◢))' },
      { name: 'Smirk', value: '( 😏 )' },
      { name: 'Stalking', value: '┬┴┬┴┤(･_├┬┴┬┴' },
      { name: 'Demon', value: 'ψ( ` ∇ ´ )ψ' },
      { name: 'Evil Laugh', value: 'Ψ(`∀´#)ﾉ' },
      { name: 'Menacing', value: 'ゴゴゴゴ' },
      { name: 'Creeping', value: '...._.' },
      { name: 'Hypnotizing', value: '(@_@)' },
      { name: 'Sharp Teeth', value: '( ` ω ´ )' },
      { name: 'Gotcha', value: 'ψ(｀▽´)ψ' },
      { name: 'Whispering Secret', value: '( ´ﾉω`)' },
      { name: 'I see you', value: '( ⚭_⚭)' },
      { name: 'You\'re next', value: '次は君だ' },
      { name: 'Trap', value: '罠' },
      { name: 'Lurking', value: '(ㅎ-ㅎ)' },
    ],
  },
  {
    category: 'Funny & Quirky',
    kaomojis: [
      { name: 'Lenny Face', value: '( ͡° ͜ʖ ͡°)' },
      { name: 'Look of Disapproval', value: '(ಠ_ಠ)' },
      { name: 'Gimme', value: '(つ◕_◕)つ' },
      { name: 'Why', value: '(´･_･`)' },
      { name: 'Table Set', value: '┬─┬ノ( º _ ºノ)' },
      { name: 'Fast Run', value: 'C= C= C= ┌(;・ω・)┘' },
      { name: 'Wobble', value: '(～￣▽￣)～' },
      { name: 'Derp', value: '( ﾟ∀ ﾟ)' },
      { name: 'Nosebleed', value: '(* ´ ▽ ` *)ﾉﾞ' },
      { name: 'Drooling', value: '(´﹃｀)' },
      { name: 'This is fine', value: '(´ー｀)' },
      { name: 'Awkward Turtle', value: '~(´・ω・`)~' },
      { name: 'Blowing Raspberry', value: ':Ｐ' },
      { name: 'Silly Dance', value: '⁽⁽◝( •௰• )◜⁾⁾' },
      { name: 'Dramatic Gasp', value: 'Σ(°ロ°)' },
      { name: 'Mind Blown', value: 'ミ๏ｖ๏彡' },
      { name: 'Spitting Drink', value: '( 뿜 )' },
      { name: 'Mustache Man', value: '(´・( moustache )・｀)' },
      { name: 'Trying to be cool', value: '( cool )' },
      { name: 'Flexing', value: 'ᕙ(⇀‸↼‶)ᕗ' },
      { name: 'Running away from responsibility', value: 'ε=┌(；・∀・)┘' },
      { name: 'I have no idea', value: '¯\\_(⊙_ʖ⊙)_/¯' },
      { name: 'Procrastinating', value: '明日から本気出す' },
    ],
  },
];